# Site settings
baseurl: ""

# Color settings (Hex value without #)
color_alpha: FFFAF6
color_beta: 0051FF

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Instagram API
instagram_key: 1988967361.1677ed0.f28e3db2bc374dffa10b9dc3173c1895
instagram_caption: false

# SEO settings
title: John Maitland
description: designer
url: ""
email: hello@johnmtlnd.com
twitter_username: johnmtlnd
default_img: ../assets/images/headshot.png

# Profile settings
social:
  twitter: http://twitter.com/johnmtlnd
  dribbble: http://dribbble.com/johnmtlnd
  instagram: http://instagram.com/johnmtlnd

location:
  neighborhood: Forest View
  city: RVA
  state: Virginia

job:
  place: Campfire & Co.
  title: Designer

# Build settings
exclude: ["node_modules", "gulpfile.js", "assets/js/app.js", "README.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /projects/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-sitemap, octopress-autoprefixer]
