# Site settings
title: John Maitland
description: John Maitland is a designer in Richmond, VA working for Campfire & Co.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
