# Permalinks
permalink:           none

# Setup
title:               John Maitland
tagline:             Designer & Programmer
url:                 johnmtlnd.com
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

navigation:
 - title: Projects
   url: /index.html
 - title: Profile
   url: /about
 - title: Blog
   url: /blog

# About/contact
author:
  name:              John Maitland
  url:               https://twitter.com/johnmtlnd
  email:             hellojohnmtlnd.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/johnmtlnd
  - title: instagram
    url: http://instagram.com/johnmtlnd
  - title: github
    url: http://github.com/johnmtlnd
  - title: dribbble
    url: http://dribbble.com/johnmtlnd
# Postal address (add as many lines as necessary)
address:
  - line: 500 Hull St.
  - line: Richmond, VA 23224

# Credits content
credits: 'Made with Jekyll.<br> Hosted by Github Pages.'

cdn_path: /public/assets


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
