# site
title: John Maitland
baseurl: ""
url: "http://johnmtlnd.com"
favicon: "/assets/sample/favicon.ico"
g_analytics: UA-12345678-1

# bio
header: John Maitland
desc: >
  Hello. I am a multi-hyphenated designer & front-end developer working for Campfire & Co. in Richmond, VA. > I work across disciplines and mediums to create meaningful and well-crafted design systems, brands, typography and drawings. If I am not running, hiking, or biking I am probably engaging in my own personal creative work.

# posts
date_format: "%Y"
post_title: Project
post_date: Year
post_cat: Category

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item
